version: "3.8"

services:
  flask-app:
    build: .
    container_name: ecommerce-app
    ports:
      - "5000:5000"
    volumes:
      - sqlite-data:/app
    restart: always

volumes:
  sqlite-data:
